apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector: # <--- This is the selector that matches the labels in the deployment
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      port: 3003
      targetPort: 3000
      protocol: TCP
      nodePort: 30001
