apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector: # <--- This is the selector that matches the labels in the deployment
    app: goserver
  type: LoadBalancer
  ports:
    - name: goserver-service
      port: 80
      targetPort: 8000
      protocol: TCP
